# Default values for httpapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace : httpapp
replicaCount: 2

image:
  repository: sampleappprodprimarysampleappacr.azurecr.io/httpapp
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: LoadBalancer
  port: 80

envs:
  DBPASS:
    secret: httpapp-dbpass
    key: password
  DBNAME: sampleappdb
  DBHOST: sampleappsampledb-failover-group.database.windows.net
  DBVERSION: MSSQL
  DBPORT: 1433
  DBUSER: appuser

dbsecretname: httpapp-dbpass
#dbsecretpassword: 
# helm install httpapp httpapp --values httpapp/values.yaml --set dbsecretpassword=$PASSWORD
#helm upgrade httpapp httpapp --values httpapp/values.yaml --set dbsecretpassword=$PASSWORD